import { CartItem } from "@/contexts/CartContext";

export const THEME_MODES = {
  LIGHT: "light",
  DARK: "dark",
};

export const candles: CartItem[] = [
  {
    id: 1,
    price: 19.99,
    name: "Spiced Cinnamon",
    shortDesc: "A warm and cozy cinnamon aroma.",
    description:
      "A rich blend of spiced cinnamon that evokes the comfort of home and festive memories.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 2,
    price: 24.99,
    name: "vanilla Embrace",
    shortDesc: "A comforting and creamy vanilla scent.",
    description:
      "A luscious vanilla fragrance that wraps you in warmth and sweetness, perfect for relaxation.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 3,
    price: 22.5,
    name: "Berry Cheesecake",
    shortDesc: "A delightful mix of berries and creamy cheesecake.",
    description:
      "A mouthwatering fusion of ripe berries and rich, buttery cheesecake that fills your space with sweetness.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 4,
    price: 21.99,
    name: "Coffee Glow",
    shortDesc: "The bold and inviting aroma of fresh coffee.",
    description:
      "Wake up to the energizing scent of freshly brewed coffee, infused with subtle caramel undertones for extra warmth.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 5,
    price: 26.99,
    name: "Suger cookie",
    shortDesc: "A sweet and buttery cookie delight.",
    description:
      "Experience the comforting aroma of freshly baked sugar cookies, with hints of vanilla and caramelized sugar.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 6,
    price: 23.99,
    name: "It Girl",
    shortDesc: "A chic and luxurious fragrance.",
    description:
      "A sophisticated blend of floral and musky notes, designed for those who love elegance and confidence.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 7,
    price: 19.99,
    name: "cherry Wine",
    shortDesc: "A rich and fruity cherry-infused aroma.",
    description:
      "A bold fusion of deep red cherries and a hint of velvety wine, creating an intoxicating and luxurious scent.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 8,
    price: 19.99,
    name: "Rose & Rouge",
    shortDesc: "A romantic and floral rose bouquet.",
    description:
      "A classic and timeless fragrance featuring fresh roses blended with soft powdery notes for a graceful finish.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 9,
    price: 19.99,
    name: "citrus Mist",
    shortDesc: "A bright and zesty citrus medley.",
    description:
      "A refreshing burst of orange, lemon, and lime, perfect for uplifting your mood and brightening your space.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 10,
    price: 19.99,
    name: "Flaming Hot",
    shortDesc: "A bold and spicy fiery scent.",
    description:
      "Ignite your senses with a daring mix of chili, cinnamon, and warm spices that bring intense energy to any room.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 11,
    price: 19.99,
    name: "Oud Essence",
    shortDesc: "A rich and luxurious oud fragrance.",
    description:
      "Experience the deep and mysterious aroma of oud, blended with warm and woody undertones to create an elegant and sophisticated atmosphere.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 12,
    price: 19.99,
    name: "Forbidden Musk",
    shortDesc: "A bold and seductive musk aroma.",
    description:
      "Unleash an irresistible allure with this sultry musk blend, exuding warmth, mystery, and timeless elegance.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 13,
    price: 19.99,
    name: "Crimson Amber",
    shortDesc: "A warm amber-infused glow.",
    description:
      "An enchanting mix of rich amber and deep red spices, creating an intoxicating scent that fills your space with warmth and depth.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 14,
    price: 19.99,
    name: "You are the one",
    shortDesc: "A romantic and enchanting scent.",
    description:
      "A captivating fragrance inspired by love and passion, blending soft florals with a touch of sweetness for a scent as unforgettable as you",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 15,
    price: 19.99,
    name: "Into the night",
    shortDesc: "A dark and mysterious aroma.",
    description:
      "Dive into the night with this alluring fragrance, blending deep, sensual notes with a hint of mystery for an unforgettable experience.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 16,
    price: 19.99,
    name: "Iced Latte",
    shortDesc: "A creamy and energizing Caffeine aroma.",
    description:
      "A refreshing fusion of aromatic coffee, creamy vanilla, and subtle sweet notes, inspired by your favorite iced lattes. Whether infused with the calming essence of lavender, the energizing aroma of espresso, or the earthy touch of matcha, this candle creates a cozy yet invigorating atmosphere, perfect for any moment of the day",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 17,
    price: 19.99,
    name: "Lavender Bliss",
    shortDesc: "Relaxing lavender-scented candle.",
    description:
      "A soothing blend of lavender essential oils designed to calm your mind and create a peaceful atmosphere.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 18,
    price: 19.99,
    name: "Lavender Bliss",
    shortDesc: "Relaxing lavender-scented candle.",
    description:
      "A soothing blend of lavender essential oils designed to calm your mind and create a peaceful atmosphere.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 19,
    price: 19.99,
    name: "Lavender Bliss",
    shortDesc: "Relaxing lavender-scented candle.",
    description:
      "A soothing blend of lavender essential oils designed to calm your mind and create a peaceful atmosphere.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 20,
    price: 19.99,
    name: "Lavender Bliss",
    shortDesc: "Relaxing lavender-scented candle.",
    description:
      "A soothing blend of lavender essential oils designed to calm your mind and create a peaceful atmosphere.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 21,
    price: 19.99,
    name: "Lavender Bliss",
    shortDesc: "Relaxing lavender-scented candle.",
    description:
      "A soothing blend of lavender essential oils designed to calm your mind and create a peaceful atmosphere.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 22,
    price: 19.99,
    name: "Lavender Bliss",
    shortDesc: "Relaxing lavender-scented candle.",
    description:
      "A soothing blend of lavender essential oils designed to calm your mind and create a peaceful atmosphere.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 23,
    price: 19.99,
    name: "Lavender Bliss",
    shortDesc: "Relaxing lavender-scented candle.",
    description:
      "A soothing blend of lavender essential oils designed to calm your mind and create a peaceful atmosphere.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 24,
    price: 19.99,
    name: "Lavender Bliss",
    shortDesc: "Relaxing lavender-scented candle.",
    description:
      "A soothing blend of lavender essential oils designed to calm your mind and create a peaceful atmosphere.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 25,
    price: 19.99,
    name: "Lavender Bliss",
    shortDesc: "Relaxing lavender-scented candle.",
    description:
      "A soothing blend of lavender essential oils designed to calm your mind and create a peaceful atmosphere.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 26,
    price: 19.99,
    name: "Lavender Bliss",
    shortDesc: "Relaxing lavender-scented candle.",
    description:
      "A soothing blend of lavender essential oils designed to calm your mind and create a peaceful atmosphere.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 27,
    price: 19.99,
    name: "Lavender Bliss",
    shortDesc: "Relaxing lavender-scented candle.",
    description:
      "A soothing blend of lavender essential oils designed to calm your mind and create a peaceful atmosphere.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 28,
    price: 19.99,
    name: "Lavender Bliss",
    shortDesc: "Relaxing lavender-scented candle.",
    description:
      "A soothing blend of lavender essential oils designed to calm your mind and create a peaceful atmosphere.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 29,
    price: 19.99,
    name: "Lavender Bliss",
    shortDesc: "Relaxing lavender-scented candle.",
    description:
      "A soothing blend of lavender essential oils designed to calm your mind and create a peaceful atmosphere.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
  {
    id: 30,
    price: 19.99,
    name: "Lavender Bliss",
    shortDesc: "Relaxing lavender-scented candle.",
    description:
      "A soothing blend of lavender essential oils designed to calm your mind and create a peaceful atmosphere.",
    scents: ["lavender", "flowers"],
    img: "/assets/images/img.jpg",
  },
];
export const recommendedColorForScent: Record<string, string> = {
  lavender: "purple",
  "white flower": "white",
  "champagne toast": "offwhite",
  "cinnamon spiced vanilla": "white",
  "coco chanel": "creamy",
  "dark kiss": "purple",
  "Strawberry Pound Cake": "red",
  "Pumpkin Cinnamon": "orange",
  "tobaco vanilla": "coffee",
  mocha: "coffee",
  "blue berry": "blue",
  choclate: "brown",
  "into the night": "black",
  strawberry: "white",
  "you are the one": "pink",
  "sugered vanilla": "creamy",
  "coconut sweety": "Creamy",
  amber: "peachy",
  "black opiume": "hot pink",
  "good girl": "babyblue",
  khamrah: "light amber",
  "icecream berry": "red",
  "watermelon lemon": "green",
  "marshmello caramel": "pink",
  "cotton candy": "pink",
  "elder blossom": "creamy",
  "bakarat rouge": "maroon",
  "choco biscute": "coffee",
  Fahrenheit: "maroon",
  "La vie est belle": "pale pink",
  Sauvage: "black",
  "Orange cloves": "orange",
  "Caramel apple": "peachy",
  "Chocolate hazelnut": "light brown",
  "Amber chocolate": "black",
  "Vanilla sandalwood": "white",
  "sweet vanilla": "pale pink",
  "black hourse": "black",
  "dolce and gabbana the one men": "navy",
  "silver scent deep bogart": "white",
  "terre de hermes": "navy",
};

export const candlesColors = [
  "light brown",
  "pale pink",
  "maroon",
  "light amber",
  "hot pink",
  "offwhite",
  "black",
  "white",
  "red",
  "pink",
  "purple",
  "creamy",
  "coffee",
  "yellow",
  "violet",
  "mint",
  "grey",
  "green",
  "lavender",
  "blue",
  "babyblue",
  "navy",
  "brown",
  "orange",
  "peachy",
];
export const candleScents = [
  "champagne toast",
  "cinnamon spiced vanilla",
  "coco chanel",
  "cinnamon spiced vanilla",
  "dark kiss",
  "cinnamon spiced vanilla",
  "Strawberry Pound Cake",
  "Pumpkin Cinnamon",
  "tobaco vanilla",
  "mocha",
  "oud",
  "white flower",
  "blue berry",
  "choclate",
  "into the night",
  "strawberry",
  "you are the one",
  "sugered vanilla",
  "coconut sweety",
  "amber",
  "black opiume",
  "good girl",
  "khamrah",
  "icecream berry",
  "watermelon lemon",
  "marshmello caramel",
  "cotton candy",
  "elder blossom",
  "bakarat rouge",
  "choco biscute",
  "Fahrenheit",
  "La vie est belle",
  "Sauvage",
  "Orange cloves",
  "Caramel apple",
  "Chocolate hazelnut",
  "Amber chocolate",
  "Vanilla sandalwood",
  "sweet vanilla",
  "black hourse",
  "dolce and gabbana the one men",
  "silver scent deep bogart",
  "terre d'hermes",
];
